services:
  server:
    image: ads/server
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      RPC_PORT: "7777"
      CACHE_HOST: "cache"
      CACHE_PORT: "6379"
    depends_on:
      cache:
        condition: service_healthy

  client:
    image: ads/client
    build:
      context: .
      dockerfile: client.Dockerfile
    environment:
      LOAD_BALANCER_HOST: "server"
      LOAD_BALANCER_PORT: "7777"
    depends_on:
      - server

  cache:
    image: redis:latest
    environment:
      REDIS_ARGS: "--protected-mode no"
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 5s
        timeout: 3s
        retries: 5
        start_period: 10s
